spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:testjdbc
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
#        maxRetryAttempts: 5 #old
        maxAttempts: 5 #new
        waitDuration: 1s
        enableExponentialBackoff: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitedRefreshPeriod: 10s
  bulkhead:
    instances:
      default:
       maxConcurrentCalls: 10
      sample-api:
       maxConcurrentCalls: 10
#spring.
#  spring.datasource.url=jdbc:h2:mem:testjdbc
#  spring.h2.console.enabled=true
#  spring.jpa.defer-datasource-initialization=true